[theme]
primaryColor = "#FF9800"
backgroundColor = "#1E2A38"
secondaryBackgroundColor = "#2C3E50"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false